server:
  servlet:
    context-path: /task-mgmt-service/v1
spring:
  data:
    mongodb:
      authentication-database: admin
      database: ${MONGO_DATABASE}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      auto-index-creation: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASSWORD}
app:
  auth:
    security:
      apis:
        public-endpoints:
          - method: GET
            uris:
              - /swagger-ui/**
              - /v3/api-docs/**
        private-endpoints:
          - uris:
      cors:
        allowed-origins: '*'
        allowed-methods: GET,POST,PUT,DELETE
        allowed-headers:
        exposed-headers:
  gateway-api-prefix: ${GATEWAY_API_PREFIX:}
  messaging:
    queues:
      notifications: notifications